services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3001}:80"
    environment:
      - VITE_API_URL=${BACKEND_URL:-http://backend:${BACKEND_PORT:-5001}/api}
    depends_on:
      - backend
    networks:
      - ticket-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-5001}:5001"
    environment:
      - PORT=5001
    networks:
      - ticket-network

networks:
  ticket-network:
    driver: bridge
